
spring:
  kafka:
    streams:
      bootstrap-servers: localhost:9092
      application-id: codat-data-stream-processor
    properties:
      default:
        deserialization:
          exception:
#            handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
            handler: exceptionhandler.com.jil.codat.StreamsDeserializationExceptionHandler
        production:
          exception:
            handler: com.jil.codat.exceptionhandler.StreamsProductionExceptionHandler

data-stream-processor:
  topics:
    - consumeTopic: Accounts_CODAT
      mappings:
        - produceTopic: Accounts_CODAT_BQ
          transformationStrategy:
            transformer: JoltTransformer
            spec: file:/Users/jialiu9/Documents/Work/LBG-CD&A/codat-data-stream-processor4/config/Accounts_CODATToAccounts_CODAT_BQ.joltSpec
            filter:
              companyIds:
                - 3fa85f64-5717-4562-b3fc-2c963f66afa6
              status: Active
        - produceTopic: Accounts_CoBa
          transformationStrategy:
            transformer: JoltTransformer
            spec: file:/Users/jialiu9/Documents/Work/LBG-CD&A/codat-data-stream-processor4/config/Accounts_CODATToAccounts_CoBa.joltSpec
            filter:
              companyIds:
                - 3fa85f64-5717-4562-b3fc-2c963f66afa6
              status: Active
    - consumeTopic: Invoices_CODAT
      mappings:
        - produceTopic: Invoices_CODAT_BQ
          transformationStrategy:
            transformer: JoltTransformer
            spec: file:/Users/jialiu9/Documents/Work/LBG-CD&A/codat-data-stream-processor4/config/NoChangeTransformation_forTest.joltSpec
            filter:
              companyIds:
                - 3fa85f64-5717-4562-b3fc-2c963f66afa6
              status: Active
        - produceTopic: Invoices_CoBa
          transformationStrategy:
            transformer: JoltTransformer
            spec: file:/Users/jialiu9/Documents/Work/LBG-CD&A/codat-data-stream-processor4/config/Invoices_CODATToInvoices_CoBa.joltSpec
            filter:
              companyIds:
                - 3fa85f64-5717-4562-b3fc-2c963f66afa6
              status: Active
